apiVersion: apps/v1 
kind: Deployment
metadata:
  namespace: default
  name: spring 
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring 
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: spring 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: spring
  labels:
    name: spring
    app: spring
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  selector:
    app: spring

